servers:
  filesystem:
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-filesystem", "${workspace}"]
    env: {}
  git:
    command: "npx"
    args: ["-y", "@cyanheads/git-mcp-server"]
    env:
      MCP_LOG_LEVEL: "info"
  auto_advisor:
    command: "/home/laptopez/4to/segundo/redes/MCP_AutoAdvisor_Server/.venv/bin/python"
    args: ["/home/laptopez/4to/segundo/redes/MCP_AutoAdvisor_Server/server.py"]
    env: {}
  pokevgc:
    command: "${POKEVGC_PY}"
    args: ["-u", "-m", "server.main"]
    cwd: "${POKEVGC_PATH}"
    env:
      PYTHONPATH: "${POKEVGC_PATH}"
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: "WARNING"
  chatbot_server:
    command: "${CHATBOT_SERVER_PY}"
    args: ["server.py", "stdio"]
    cwd: "${CHATBOT_SERVER_PATH}"
    env:
      PYTHONUNBUFFERED: "1"
  remote_echo:
    command: "ssh"
    args:
      - "-T"
      - "-i"
      - "${SSH_KEY_PATH}"
      - "-o" 
      - "BatchMode=yes"
      - "-o"
      - "StrictHostKeyChecking=accept-new"
      - "-o"
      - "ConnectTimeout=8"
      - "-o"
      - "ServerAliveInterval=10"
      - "-o"
      - "ServerAliveCountMax=2"
      - "${REMOTE_SSH}"
      - "bash"
      - "-lc"
    env:
      PYTHONUNBUFFERED: "1"